# Generated by Django 5.2.15 on 2026-07-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('RENTAL', 'Rental'), ('CONDO', 'Condo')], max_length=20)),
                ('address', models.TextField()),
                ('total_units', models.PositiveIntegerField(default=1)),
                ('occupied_units', models.PositiveIntegerField(default=0)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
