# Generated by Django 5.2.15 on 2026-07-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_property_description_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('FULL', 'Fully Occupied'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('RENTAL', 'Rental House'), ('CONDO', 'Condominium'), ('HOSTEL', 'Hostel'), ('OFFICE', 'Office'), ('SHOP', 'Commercial Shop')], max_length=20),
        ),
    ]
